data:
  batch_size: 16
  img_size:
  - 512
  - 1024
  num_workers: 16
  root_dir: /home/jianglh1/Cityscapes/data
  use_augmentation: true
  use_strong_aug: true
logging:
  use_wandb: false
  wandb_project: cityscapes_segmentation
model:
  name: unet
  num_classes: 19
project:
  description: "\u4F7F\u7528SGD\u4F18\u5316\u5668\u548C\u4F59\u5F26\u9000\u706B\u8C03\
    \u5EA6\u5668"
  name: Cityscapes_Semantic_Segmentation_SGD_Cosine
save:
  dir: ./results_sgd_cosine
  save_frequency: 10
seed:
  deterministic: true
  value: 42
training:
  device: cuda
  learning_rate: 0.01
  momentum: 0.9
  nesterov: true
  num_epochs: 60
  optimizer: sgd
  scheduler: cosine
  scheduler_config:
    eta_min: 1.0e-05
    warmup_epochs: 5
  use_amp: true
  weight_decay: 0.0001
